### ISSUE TITLE
Fix the Rails bug in a better way.

### ISSUE THREAD

**Issue by ghost** [tb/northwind-graphql-ruby#27]
Maybe we can fix the issue you try to fix here: https://github.com/tb/northwind-graphql-ruby/blob/master/app/graphql/functions/create_contactable.rb

with `optional: true` in https://github.com/tb/northwind-graphql-ruby/blob/master/app/models/contact.rb

like they say here: https://github.com/rails/rails/issues/29781.

At least is better than a new function.

Maybe I will PR now.

**Comment by ghost** [comment]
Sorry for the 3 PRs, I don't know how to edit multiple files online way.

**Comment by tb** [comment]
Fix works, thanks!
